name: Deploy Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  my_job:
    name: Deploy to Staging
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test
        run: echo "Deploying to Staging"
